version: '2.1'

services:

  wp:
    image: wordpress:5.8-php7.4
    volumes:
      - ./web:/var/www/html
    ports:
      - "${WP_HTTP}:80"
      - "${WP_HTTPS}:443"
    links:
      - wpdb:mysql
    depends_on:
      - wpdb
    environment:
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    restart: unless-stopped

  wpdb:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: unless-stopped

  wpcli:
    image: tatemz/wp-cli
    volumes_from:
      - wp
    links:
      - wpdb:mysql
    entrypoint: wp
    command: "--info"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHPMY_PORT}:80'
    environment:
      PMA_HOST: wpdb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS} 
    restart: unless-stopped
    depends_on:
      - wpdb
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Boise
      - PASSWORD=${CODE_PASS}
      - SUDO_PASSWORD=${CODE_SPASS}
    volumes:
      - ./code_config:/config
      - ./web:/config/workspace
    ports:
      - ${CODE_PORT}:8443
    restart: unless-stopped

volumes:
  wp:
  wpdb:
  code-server:
  